# Generated by Django 3.2.7 on 2022-08-06 10:06

import coach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to=coach.models.user_directory_path),
        ),
    ]
