# Generated by Django 4.0.5 on 2022-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='available_days',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
