# Generated by Django 4.0.5 on 2022-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_remove_coach_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
