# Generated by Django 4.0.5 on 2022-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_coach_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='gender',
        ),
        migrations.AddField(
            model_name='coach',
            name='timing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
