# Generated by Django 4.0.5 on 2022-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_coach_gender_coach_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
