# Generated by Django 4.0.5 on 2022-06-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_coach_full_name_coach_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
