# Generated by Django 4.0.5 on 2022-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_coach_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
