# Generated by Django 4.0.5 on 2022-07-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=550),
        ),
    ]
