# Generated by Django 4.0.5 on 2022-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_alter_service_options_service_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
