# Generated by Django 4.0.5 on 2022-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_alter_coach_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
