# Generated by Django 4.0.5 on 2022-07-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0019_alter_coach_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rating',
        ),
    ]
