# Generated by Django 4.0.5 on 2022-07-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0022_coach_avg_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='avg_score',
        ),
    ]
