# Generated by Django 4.0.5 on 2022-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0024_alter_coach_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['user', 'id'], name='coach_coach_user_id_e157a3_idx'),
        ),
    ]
