# Generated by Django 4.0.5 on 2022-07-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0025_coach_coach_coach_user_id_e157a3_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coach',
            name='coach_coach_user_id_e157a3_idx',
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['user', 'id', 'paid', 'category'], name='coach_coach_user_id_21652d_idx'),
        ),
    ]
