# Generated by Django 4.0.5 on 2022-07-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0028_service_coach_servi_related_a80a6b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coach',
            name='coach_coach_user_id_54f7ae_idx',
        ),
    ]
