# Generated by Django 4.0.5 on 2022-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0029_remove_coach_coach_coach_user_id_54f7ae_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['user', 'id', 'paid', 'category', 'full_name', 'location'], name='coach_coach_user_id_54f7ae_idx'),
        ),
    ]
