# Generated by Django 4.0.5 on 2022-07-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0030_coach_coach_coach_user_id_54f7ae_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
    ]
