# Generated by Django 4.0.5 on 2022-07-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0007_alter_planlist_id_alter_planlistdetail_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('selected_subscription_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_sub', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
