# Generated by Django 3.2.7 on 2022-07-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0007_auto_20220726_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug_field', models.SlugField(blank=True, unique=True)),
                ('selected_subscription_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_sub', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
