# Generated by Django 3.2.7 on 2022-07-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20220727_0943'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsubscriptionplan',
            name='selected_subscription_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_sub', to='subscriptions.subscriptionplan'),
        ),
    ]
