# Generated by Django 4.0.5 on 2022-07-08 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_customsubscriptionplan_selected_subscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsubscriptionplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
