# Generated by Django 4.0.5 on 2022-07-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_planlist_id_alter_planlistdetail_id_and_more'),
        ('subscription', '0006_alter_customsubscriptionplan_selected_subscription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsubscriptionplan',
            name='selected_subscription_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_sub', to='subscriptions.subscriptionplan'),
        ),
    ]
