# Generated by Django 3.2.7 on 2022-07-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_summary', models.TextField()),
                ('review_description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['coach', 'reviewer'], name='reviews_rev_coach_i_474844_idx'),
        ),
    ]
