# Generated by Django 4.0.5 on 2022-06-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_address_phone_number'),
        ('coach', '0014_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_summary', models.TextField()),
                ('review_description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
