# Generated by Django 4.0.5 on 2022-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['coach', 'reviewer'], name='reviews_rev_coach_i_474844_idx'),
        ),
    ]
