# Generated by Django 4.0.5 on 2022-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
