# Generated by Django 4.0.5 on 2022-07-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deactivateuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='DeactivateUser',
        ),
    ]
