# Generated by Django 4.0.5 on 2022-07-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_deactivateuser_user_delete_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'id', 'paid'], name='user_profil_user_id_655f2e_idx'),
        ),
    ]
