# Generated by Django 4.0.5 on 2022-07-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_user_profil_user_id_655f2e_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
